Error Boundaries(에러 경계) : componentDidCatch 메소드를 가지고 있는 컴포넌트

클래스 컴포넌트를 오류 경계로 만들기 위해서는 생명 주기 함수 componentDidCatch()를 사용해야 한다.
어플리케이션 이용중 오류가 발생하더라도 어플리케이션 전체가 중단되지 않고 오류를 확인시켜주기 위해 사용한다.

componentDidCatch : 
    하위 컴포넌트 중 하나가 오류를 만들거나 전달할 때 실행된다.
    인자로는 발생한 오류를 객체형태로 받는다.

                    

사용 예시 )

<!-- ErrorBoundary 컴포넌트 -->
class ErrorBoundary extends Component {
    constructor() {
        super();
        this.state = { hasError: false };
    }

    componentDidCatch(error) {
        console.log('오류 발생');
        this.setState({ hasError: true });
    }

    render() {
        if(this.state.hasError) {
            return <p>오류 발생</p>
        }
        return this.props.children;
    }
}

<!-- 오류가 발생할 컴포넌트 -->
class ErrorComponent extends Component {
    componentDidMount() {
        throw new Error('error!')
    }

    render() {
        return (
            <p>오류 발생 안하면 보여질 문구</p>
        )
    }
}

<!-- App 컴포넌트 -->
const App = () => {
    return (
        <ErrorBoundary>
            <ErrorComponent />
        </ErrorBoundary>
    )
}

동작 순서
1. ErrorComponent가 마운트 되면서 오류 발생 시킴
2. ErrorBoundary가 오류를 감지해서 hasError의 state값을 true로 변경
3. ErrorBoundary render에서 props.children이 아닌 "오류 발생" 문구를 return함
4. 화면에 "오류 발생" 표출
5. 개발시에는 경고창이 뜨지만 배포를 하면 경고창은 보이지 않음